import test from 'node:test';
import assert from 'node:assert/strict';
import { createRoomState, transitionRoom, projectRoomState, ROOM_LIMITS } from '../share/room-state.mjs';

const base = () => createRoomState({ roomId: 'ABCDEFGH', openedAt: 1000, expiresAt: 22000 });
const host = (type, extra = {}) => ({ type, role: 'host', at: 2000, ...extra });
const listener = (type, extra = {}) => ({ type, role: 'listener', actorId: 'p1', participantId: 'p1', at: 2000, ...extra });
const joined = () => transitionRoom(base(), listener('joined', { name: '  Ada  ' })).state;
const submitted = () => transitionRoom(joined(), listener('request-submitted', { requestId: 'q1', idea: 'rain', vibe: 'soft', language: 'Hindi' })).state;
const accepted = () => transitionRoom(submitted(), host('request-accepted', { requestId: 'q1' })).state;

test('room creation is versioned', () => assert.deepEqual(base(), { version: 1, roomId: 'ABCDEFGH', openedAt: 1000, expiresAt: 22000, expiredAt: null, hostPresent: false, participants: [], kickedParticipantIds: [], queue: [], currentRecording: null, currentSong: null, setlist: [] }));
test('join leave and rejoin normalize names', () => { let s = joined(); assert.equal(s.participants[0].name, 'Ada'); s = transitionRoom(s, listener('left')).state; assert.equal(s.participants[0].connected, false); s = transitionRoom(s, listener('joined')).state; assert.equal(s.participants[0].connected, true); });
test('listener cap is enforced', () => { let s = base(); for (let i=0;i<ROOM_LIMITS.listeners;i++) s = transitionRoom(s, { type:'joined', role:'listener', participantId:`p${i}`, at:i }).state; assert.equal(transitionRoom(s, { type:'joined', role:'listener', participantId:'overflow' }).error.code, 'room-full'); });
test('payload limits are enforced', () => { assert.equal(transitionRoom(base(), listener('joined', { name:'x'.repeat(41) })).error.code, 'invalid-name'); assert.equal(transitionRoom(joined(), listener('request-submitted', { requestId:'q', idea:'x'.repeat(201) })).error.code, 'invalid-request'); });
test('submissions are FIFO and capped', () => { let s=joined(); for(let i=0;i<50;i++) s=transitionRoom(s, listener('request-submitted',{requestId:`q${i}`,idea:`song ${i}`})).state; assert.equal(s.queue[0].id,'q0'); assert.equal(transitionRoom(s,listener('request-submitted',{requestId:'qx',idea:'x'})).error.code,'queue-full'); });
test('host manages queue and listener cannot', () => { const s=submitted(); assert.equal(transitionRoom(s, listener('request-accepted',{requestId:'q1'})).error.code,'host-only'); assert.equal(transitionRoom(s, host('request-accepted',{requestId:'q1'})).state.queue[0].status,'accepted'); });
test('reorder and decline require valid transitions', () => { let s=submitted(); s=transitionRoom(s, listener('request-submitted',{requestId:'q2',idea:'sun'})).state; s=transitionRoom(s,host('request-reordered',{requestId:'q2',toIndex:0})).state; assert.equal(s.queue[0].id,'q2'); s=transitionRoom(s,host('request-declined',{requestId:'q2'})).state; assert.equal(s.queue[0].status,'declined'); });
test('only one recording and failure restores accepted', () => { let s=accepted(); s=transitionRoom(s,host('recording-started',{requestId:'q1'})).state; assert.equal(transitionRoom(s,host('recording-started',{requestId:'q1'})).error.code,'recording-active'); s=transitionRoom(s,host('recording-failed',{requestId:'q1'})).state; assert.equal(s.queue[0].status,'accepted'); });
test('lyrics and ready populate current song', () => { let s=transitionRoom(accepted(),host('recording-started',{requestId:'q1'})).state; s=transitionRoom(s,host('lyrics-ready',{requestId:'q1',lyrics:{title:'Rain',language:'Hindi',lyricsNative:'बारिश',lyricsRoman:'baarish',prompt:'secret'}})).state; s=transitionRoom(s,host('song-ready',{requestId:'q1',shareId:'abcdefghijklmnop',startedAt:5000})).state; assert.equal(s.currentSong.lyrics.prompt,undefined); assert.equal(projectRoomState(s,{role:'listener'}).currentSong.startedAt,5000); });
test('prior songs enter capped setlist', () => { let s=base(); s.currentSong={shareId:'aaaaaaaaaaaaaaaa',title:'A',language:'x',startedAt:1,lyrics:{}}; s.participants=[{id:'p1',name:'A',connected:true}]; s.queue=[{id:'q1',participantId:'p1',status:'recording'}]; s.currentRecording={requestId:'q1',lyrics:{title:'B',language:'y'}}; s=transitionRoom(s,host('song-ready',{requestId:'q1',shareId:'bbbbbbbbbbbbbbbb',startedAt:2})).state; assert.deepEqual(s.setlist[0],{shareId:'aaaaaaaaaaaaaaaa',title:'A',language:'x',startedAt:1}); });
test('projections hide participant ids from listeners', () => { const s=submitted(); assert.equal(projectRoomState(s,{role:'host'}).participants[0].id,'p1'); assert.equal(projectRoomState(s,{role:'listener',participantId:'p1'}).participants[0].id,undefined); });
test('input state is immutable', () => { const s=submitted(); const before=JSON.stringify(s); transitionRoom(s,host('request-accepted',{requestId:'q1'})); assert.equal(JSON.stringify(s),before); });
test('kick blocks identity rejoin', () => { let s=transitionRoom(joined(),host('kicked',{participantId:'p1'})).state; assert.equal(transitionRoom(s,listener('joined')).error.code,'kicked'); });
test('expiry is terminal', () => { const s=transitionRoom(base(),{type:'room-expired',role:'host',at:999}).state; assert.equal(transitionRoom(s,listener('joined')).error.code,'room-expired'); });
test('lyrics-ready enforces share metadata ceilings',()=>{let s=transitionRoom(accepted(),host('recording-started',{requestId:'q1'})).state;const valid={title:'T',language:'Hindi',nativeScriptName:'Devanagari',lyricsNative:'गीत',lyricsRoman:'geet'};for(const lyrics of [{...valid,title:'x'.repeat(121)},{...valid,language:'x'.repeat(81)},{...valid,nativeScriptName:'x'.repeat(81)},{...valid,lyricsNative:'x'.repeat(5001)},{...valid,lyricsRoman:'x'.repeat(5001)}])assert.equal(transitionRoom(s,host('lyrics-ready',{requestId:'q1',lyrics})).error.code,'invalid-lyrics');assert.equal(transitionRoom(s,host('lyrics-ready',{requestId:'q1',lyrics:valid})).state.currentRecording.lyrics.title,'T');});
