import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { roomPage } from '../share/room-page.mjs';
import { COURTYARD_SCENE } from '../share/courtyard.mjs';

test('room page escapes data and reuses the exact courtyard',()=>{const html=roomPage('ABCD<script>','nonce-value');assert.doesNotMatch(html,/<script>ABCD/);assert.match(html,/ABCD&lt;script&gt;/);assert.match(html,/nonce="nonce-value"/);assert.ok(html.includes(COURTYARD_SCENE));});
test('room page provides join request peek player and setlist surfaces',()=>{const html=roomPage('ABCDEFGH','n');for(const text of ['Join the mehfil 🔊','id="request"','Don\'t click me','id="audio"','Setlist','aria-live="polite"'])assert.ok(html.includes(text),text);});
test('room client uses same-origin paths and session-only credentials',()=>{const html=roomPage('ABCDEFGH','n');assert.match(html,/sessionStorage/);assert.doesNotMatch(html,/localStorage/);assert.match(html,/\/rooms\/'\+roomId\+'\/ws/);assert.match(html,/\/s\/'\+song\.shareId\+'\/audio/);assert.match(html,/Date\.now\(\)-song\.startedAt/);});
test('room client reconnects and keeps playback rejection visible',()=>{const html=roomPage('ABCDEFGH','n');assert.match(html,/Math\.min\(1000\*2\*\*retry,30000\)/);assert.match(html,/Playback needs another tap/);assert.match(html,/await audio\.play\(\)/);});
test('room page contains no token or upload credential fields',()=>{const html=roomPage('ABCDEFGH','n');assert.doesNotMatch(html,/MiniMax.*token|MEHFIL_SHARE_SECRET|uploadSecret|localStorage/);});
test('new songs seek, attempt playback, pace lyrics, and restore retry after rejection',async()=>{const html=roomPage('ABCDEFGH','n'),scripts=[...html.matchAll(/<script(?: nonce="n")?>([\s\S]*?)<\/script>/g)];const source=scripts.at(-1)[1];class Element{constructor(){this.hidden=false;this.textContent='';this.children=[];this.listeners={};this.classNames=new Set();this.classList={add:x=>this.classNames.add(x),remove:x=>this.classNames.delete(x)};this.options=[];this.duration=100;this.currentTime=0;this.paused=true;this.attrs={}}addEventListener(type,fn,options){(this.listeners[type]||=[]).push({fn,once:Boolean(options?.once)})}async emit(type,event={}){for(const item of [...(this.listeners[type]||[])]){await item.fn(event);if(item.once)this.listeners[type]=this.listeners[type].filter(value=>value!==item)}}replaceChildren(...children){this.children=children}append(...children){this.children.push(...children)}setAttribute(name,value){this.attrs[name]=String(value)}getAttribute(name){return this.attrs[name]||null}reset(){}}
const elements=new Map(),element=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id)};element('room-data').textContent=JSON.stringify({roomId:'ABCDEFGH'});element('name').value='Ada';const audio=element('audio');let playCalls=0,loadCalls=0,rejectPlayback=false;audio.play=async()=>{playCalls+=1;if(rejectPlayback)throw new Error('blocked');audio.paused=false};audio.pause=()=>{audio.paused=true};audio.load=()=>{loadCalls+=1};const scene=element('scene');const document={querySelector(selector){return selector==='.scene'?scene:element(selector.replace(/^#/,''))},createElement(){return new Element()}};const store=new Map();const sessionStorage={getItem:key=>store.get(key)||null,setItem:(key,value)=>store.set(key,value),removeItem:key=>store.delete(key)};class WebSocket{static OPEN=1;static instances=[];constructor(){this.listeners={};this.readyState=1;WebSocket.instances.push(this)}addEventListener(type,fn){(this.listeners[type]||=[]).push(fn)}send(){}close(){}async emit(type,event={}){for(const fn of this.listeners[type]||[])await fn(event)}}const context={document,sessionStorage,WebSocket,location:{origin:'https://share.example'},setTimeout:()=>0,Date,JSON,Math,URL,console};vm.runInNewContext(source,context);await element('join').emit('click');assert.equal(playCalls,1,'join tap attempts audio unlock');const socket=WebSocket.instances[0];await socket.emit('open');const snapshot=shareId=>({hostPresent:true,listenerCount:1,participants:[{name:'Ada'}],queue:[],currentRecording:null,currentSong:{shareId,title:'Rain',language:'Hindi',startedAt:Date.now()-10000,lyrics:{language:'Hindi',isLatinScript:false,lyricsNative:'पहली\nदूसरी',lyricsRoman:'pehli\ndusri'}},setlist:[],expiredAt:null});await socket.emit('message',{data:JSON.stringify({type:'snapshot',state:snapshot('aaaaaaaaaaaaaaaa')})});await audio.emit('loadedmetadata');assert.equal(loadCalls,1);assert.equal(playCalls,2,'first song attempts playback');assert.ok(audio.currentTime>=9);audio.currentTime=60;await audio.emit('timeupdate');assert.ok(element('song-lyrics').children.some(line=>line.hidden===false));assert.ok(audio.listeners.timeupdate.length);rejectPlayback=true;await socket.emit('message',{data:JSON.stringify({type:'snapshot',state:snapshot('bbbbbbbbbbbbbbbb')})});await audio.emit('loadedmetadata');assert.equal(loadCalls,2);assert.equal(playCalls,3,'second song attempts playback');assert.equal(element('play').hidden,false);assert.match(element('play-error').textContent,/another tap/);await audio.emit('play');assert.ok(scene.classNames.has('is-performing'));await audio.emit('pause');assert.equal(scene.classNames.has('is-performing'),false);});
test('terminal room failures clear unusable credentials and suppress reconnect',()=>{const html=roomPage('ABCDEFGH','n');assert.match(html,/message\.code==='resume-invalid'[\s\S]*stopRoom/);assert.match(html,/event\.code===4002[\s\S]*stopRoom/);assert.match(html,/event\.code===4004[\s\S]*stopRoom/);assert.match(html,/sessionStorage\.removeItem\(key\)/);assert.match(html,/if\(terminal\)return/);});
