import test from 'node:test';
import assert from 'node:assert/strict';
import { createRoomTransport, sha256, AUTH_TIMEOUT_MS, ABSOLUTE_ROOM_MS, EMPTY_GRACE_MS } from '../share/room-transport.mjs';

function fixture() {
  const values = new Map(); const messages=[]; const closed=[]; const alarms=[]; const attachments=new Map(); let clock=1000; let sequence=0;
  const storage={get:async k=>structuredClone(values.get(k)),put:async(k,v)=>values.set(k,structuredClone(v))};
  const transport=createRoomTransport({storage,now:()=>clock,randomId:()=>`id${++sequence}`,randomCredential:()=>`resume${sequence}`,send:(s,m)=>messages.push([s,m]),broadcast:fn=>{ for(const s of attachments.keys()) if(attachments.get(s).authenticated) messages.push([s,fn(s)]); },close:(...x)=>closed.push(x),setAttachment:(s,a)=>attachments.set(s,a),getAttachment:s=>attachments.get(s),setAlarm:async x=>alarms.push(x)});
  return {transport,values,messages,closed,alarms,attachments,tick:n=>clock+=n,now:()=>clock};
}

test('host authenticates by digest and wrong secret closes',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const s={};await f.transport.connect(s);await f.transport.message(s,JSON.stringify({type:'auth-host',secret:'wrong'}));assert.equal(f.closed[0][1],4001);});
test('listener receives credential and resumes identity',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const a={};await f.transport.connect(a);await f.transport.message(a,JSON.stringify({type:'join',name:'Ada'}));const cred=f.messages.find(([,m])=>m.type==='resume-credential')[1].credential;const id=f.attachments.get(a).participantId;const b={};await f.transport.connect(b);await f.transport.message(b,JSON.stringify({type:'join',resume:cred}));assert.equal(f.attachments.get(b).participantId,id);});
test('authentication timeout closes idle sockets',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const s={};await f.transport.connect(s);f.tick(AUTH_TIMEOUT_MS);await f.transport.checkAuthenticationTimeout(s);assert.equal(f.closed[0][2],'authentication-timeout');});
test('malformed oversized and pre-auth messages do not mutate',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const s={};await f.transport.connect(s);const before=JSON.stringify(f.values.get('state'));await f.transport.message(s,'{');await f.transport.message(s,'x'.repeat(17000));await f.transport.message(s,JSON.stringify({type:'request-submitted'}));assert.equal(JSON.stringify(f.values.get('state')),before);});
test('actor and role are derived from attachment',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const s={};await f.transport.connect(s);await f.transport.message(s,JSON.stringify({type:'join'}));await f.transport.message(s,JSON.stringify({type:'request-submitted',role:'host',actorId:'evil',participantId:'evil',idea:'rain'}));assert.equal(f.values.get('state').queue[0].participantId,f.attachments.get(s).participantId);});
test('persistence precedes snapshots and errors stay private',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const s={};await f.transport.connect(s);await f.transport.message(s,JSON.stringify({type:'join'}));assert.equal(f.values.get('state').participants.length,1);await f.transport.message(s,JSON.stringify({type:'request-accepted',requestId:'no'}));assert.equal(f.messages.at(-1)[0],s);assert.equal(f.messages.at(-1)[1].type,'error');});
test('kick closes listener and blocks credential reuse',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const l={},h={};await f.transport.connect(l);await f.transport.message(l,JSON.stringify({type:'join'}));const cred=f.messages.find(([,m])=>m.type==='resume-credential')[1].credential;const id=f.attachments.get(l).participantId;await f.transport.connect(h);await f.transport.message(h,JSON.stringify({type:'auth-host',secret:'host'}));await f.transport.message(h,JSON.stringify({type:'kicked',participantId:id}));assert.ok(f.closed.some(x=>x[0]===l));const r={};await f.transport.connect(r);await f.transport.message(r,JSON.stringify({type:'join',resume:cred}));assert.equal(f.messages.at(-1)[1].code,'resume-invalid');});
test('listener cannot revoke another resume credential by spoofing kick',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const a={},b={};await f.transport.connect(a);await f.transport.message(a,JSON.stringify({type:'join'}));const credential=f.messages.find(([,m])=>m.type==='resume-credential')[1].credential;const id=f.attachments.get(a).participantId;await f.transport.message(a,JSON.stringify({type:'kicked',participantId:id,role:'host'}));await f.transport.connect(b);await f.transport.message(b,JSON.stringify({type:'join',resume:credential}));assert.equal(f.attachments.get(b).participantId,id);});
test('disconnect schedules grace and reconnect retains absolute cap',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const s={};await f.transport.connect(s);await f.transport.message(s,JSON.stringify({type:'join'}));await f.transport.disconnect(s);assert.equal(f.values.get('meta').absoluteDeadline,1000+ABSOLUTE_ROOM_MS);assert.ok(f.values.get('meta').emptyDeadline);});
test('alarm expires and closes sockets',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host'),expiresAt:2000});const s={};await f.transport.connect(s);await f.transport.message(s,JSON.stringify({type:'join'}));f.tick(1000);await f.transport.alarm();assert.equal(f.values.get('state').expiredAt,2000);assert.ok(f.closed.length);});
test('uninitialized and expired rooms close gracefully',async()=>{const empty=fixture(),probe={};assert.equal(await empty.transport.connect(probe),false);await empty.transport.message(probe,JSON.stringify({type:'join'}));assert.deepEqual(empty.closed.map(item=>item.slice(1)),[[4004,'room-unavailable'],[4004,'room-unavailable']]);const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host'),expiresAt:1000});const socket={};await f.transport.connect(socket);assert.equal(f.closed.at(-1)[1],4004);assert.equal(f.attachments.has(socket),false);});
test('full-room admission does not authenticate or persist a rejected credential',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});for(let i=0;i<20;i++){const socket={};await f.transport.connect(socket);await f.transport.message(socket,JSON.stringify({type:'join'}));}const rejected={};await f.transport.connect(rejected);await f.transport.message(rejected,JSON.stringify({type:'join'}));assert.equal(f.attachments.get(rejected).authenticated,false);assert.equal(Object.keys(f.values.get('meta').resumeDigests).length,20);assert.ok(f.closed.some(item=>item[0]===rejected&&item[1]===4002));});
test('empty deadline is stable across unauthenticated probes and resets only around authenticated presence',async()=>{const f=fixture();await f.transport.initialize({roomId:'ABCDEFGH',hostDigest:await sha256('host')});const initial=f.values.get('meta').emptyDeadline;assert.equal(initial,f.now()+EMPTY_GRACE_MS);f.tick(1000);const probe={};await f.transport.connect(probe);await f.transport.disconnect(probe);assert.equal(f.values.get('meta').emptyDeadline,initial);const listener={};await f.transport.connect(listener);await f.transport.message(listener,JSON.stringify({type:'join'}));assert.equal(f.values.get('meta').emptyDeadline,null);await f.transport.disconnect(listener);const disconnectedDeadline=f.values.get('meta').emptyDeadline;assert.equal(disconnectedDeadline,f.now()+EMPTY_GRACE_MS);f.tick(1000);const resumed={};const credential=f.messages.find(([,message])=>message.type==='resume-credential')[1].credential;await f.transport.connect(resumed);await f.transport.message(resumed,JSON.stringify({type:'join',resume:credential}));assert.equal(f.values.get('meta').emptyDeadline,null);});
