import { COURTYARD_SCENE } from './courtyard.mjs';

const escapeHtml = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const scriptJson = value => JSON.stringify(value).replaceAll('<','\\u003c').replaceAll('>','\\u003e').replaceAll('&','\\u0026');

export function roomPage(roomId, nonce) {
  const data = scriptJson({ roomId });
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#1f4238"><title>Room ${escapeHtml(roomId)} · Mini Mehfil</title>
<style nonce="${nonce}">:root{--ink:#f9edda;--muted:#ddcbb8;--night:#142e2d;--amber:#e6a653;--terra:#7a362d}*{box-sizing:border-box}body{margin:0;min-height:100svh;color:var(--ink);background:var(--night);font-family:"Avenir Next",sans-serif}.scene,.scene svg{position:fixed;inset:0;width:100%;height:100%;z-index:-2}.scene:after{content:"";position:absolute;inset:0;background:rgba(7,25,24,.58)}main{width:min(760px,calc(100% - 28px));margin:auto;padding:32px 0 80px}.card{padding:22px;margin:16px 0;border:1px solid #ffffff35;border-radius:22px;background:#142e2de8;backdrop-filter:blur(12px)}h1,h2{font-family:Georgia,serif}label{display:block;margin:12px 0 5px}input,select,textarea,button{width:100%;padding:12px;border-radius:12px;border:1px solid #ffffff44;font:inherit}input,select,textarea{color:var(--ink);background:#081b1caa}button{margin-top:12px;color:#2b251f;background:var(--amber);font-weight:800;cursor:pointer}.secondary{color:var(--ink);background:var(--terra)}[hidden]{display:none!important}.status{min-height:1.5em;color:var(--muted)}.queue li,.setlist li{margin:.6em 0}.lyrics{white-space:pre-wrap;font:italic 18px/1.6 Georgia,serif}.player{position:sticky;bottom:12px}.player audio{width:100%}@media(max-width:360px){main{width:calc(100% - 16px)}.card{padding:16px;margin:10px 0}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important}}</style></head><body>${COURTYARD_SCENE}<main>
<header><small>LIVE MEHFIL · ${escapeHtml(roomId)}</small><h1>Come sit in the courtyard</h1><p id="status" class="status" aria-live="polite">Ready to join.</p></header>
<section id="join-panel" class="card"><h2>Join this mehfil</h2><label for="name">Your name (optional)</label><input id="name" maxlength="40" autocomplete="nickname"><button id="join" type="button">Join the mehfil 🔊</button></section>
<section id="room" hidden><section class="card"><p><strong id="listeners">0 listeners</strong> · <span id="host">Host away</span></p><form id="request"><label for="idea">What should the song be about?</label><textarea id="idea" maxlength="200" required></textarea><label for="vibe">Vibe</label><input id="vibe" maxlength="120"><label for="language">Language</label><input id="language" maxlength="40"><button>Request a song</button></form></section>
<section class="card"><h2>Request queue</h2><ol id="queue" class="queue"></ol><p id="recording"></p><button id="peek" class="secondary" type="button" hidden>Don't click me</button><div id="lyrics" class="lyrics" hidden></div></section>
<section id="player" class="card player" hidden><h2 id="song-title"></h2><audio id="audio" preload="metadata" controls></audio><button id="play" type="button">Tap to hear the mehfil</button><p id="play-error" role="alert"></p></section>
<section class="card"><h2>Setlist</h2><ol id="setlist" class="setlist"></ol></section></section></main>
<script id="room-data" type="application/json">${data}</script><script nonce="${nonce}">
const {roomId}=JSON.parse(document.querySelector('#room-data').textContent),key='mini-mehfil-room:'+roomId,status=document.querySelector('#status'),joinPanel=document.querySelector('#join-panel'),room=document.querySelector('#room'),queue=document.querySelector('#queue'),audio=document.querySelector('#audio'),play=document.querySelector('#play'),playError=document.querySelector('#play-error');let socket,retry=0,snapshot;
const wsUrl=()=>location.origin.replace(/^http/,'ws')+'/rooms/'+roomId+'/ws';
function connect(name){status.textContent=retry?'Reconnecting…':'Joining…';socket=new WebSocket(wsUrl());socket.addEventListener('open',()=>{const resume=sessionStorage.getItem(key);socket.send(JSON.stringify(resume?{type:'join',resume}:{type:'join',name}));retry=0});socket.addEventListener('message',event=>{let message;try{message=JSON.parse(event.data)}catch{return status.textContent='The room sent a malformed message.'}if(message.type==='resume-credential')sessionStorage.setItem(key,message.credential);if(message.type==='snapshot')render(message.state);if(message.type==='error'){status.textContent=message.code==='room-full'?'This mehfil is full.':message.code==='kicked'?'You were asked to leave the mehfil.':message.code}});socket.addEventListener('close',event=>{if(event.code===4003)return status.textContent='You were asked to leave the mehfil.';if(event.code===4004){sessionStorage.removeItem(key);return status.textContent='This mehfil has ended.'}status.textContent='Offline — reconnecting…';setTimeout(()=>{retry=Math.min(retry+1,6);connect(name)},Math.min(1000*2**retry,30000))})}
function send(value){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(value))}
function render(state){snapshot=state;joinPanel.hidden=true;room.hidden=false;status.textContent=state.hostPresent?'The host is here.':'Host away — requests will wait.';document.querySelector('#listeners').textContent=state.listenerCount+' listener'+(state.listenerCount===1?'':'s');document.querySelector('#host').textContent=state.hostPresent?'Host present':'Host away';queue.replaceChildren(...state.queue.map(item=>{const li=document.createElement('li');li.textContent=(item.mine?'Your request':'A request')+' — '+item.status;return li}));const recording=state.currentRecording;document.querySelector('#recording').textContent=recording?(state.queue.find(item=>item.id===recording.requestId)?.mine?'The band is recording yours':'The band is recording') : '';const peek=document.querySelector('#peek'),lyrics=document.querySelector('#lyrics');peek.hidden=!recording?.lyrics;if(recording?.lyrics){lyrics.textContent=(recording.lyrics.lyricsNative||'')+'\n\n'+(recording.lyrics.lyricsRoman||'')}const song=state.currentSong;if(song){document.querySelector('#player').hidden=false;document.querySelector('#song-title').textContent=song.title;const source='/s/'+song.shareId+'/audio';if(audio.getAttribute('src')!==source){audio.src=source;audio.addEventListener('loadedmetadata',()=>{audio.currentTime=Math.max(0,(Date.now()-song.startedAt)/1000)},{once:true})}}document.querySelector('#setlist').replaceChildren(...state.setlist.map(item=>{const li=document.createElement('li'),a=document.createElement('a');a.href='/s/'+item.shareId;a.textContent=item.title;li.append(a);return li}))}
document.querySelector('#join').addEventListener('click',()=>connect(document.querySelector('#name').value));document.querySelector('#request').addEventListener('submit',event=>{event.preventDefault();send({type:'request-submitted',idea:document.querySelector('#idea').value,vibe:document.querySelector('#vibe').value,language:document.querySelector('#language').value});event.target.reset()});document.querySelector('#peek').addEventListener('click',()=>{document.querySelector('#lyrics').hidden=false});play.addEventListener('click',async()=>{try{await audio.play();play.hidden=true;playError.textContent=''}catch{play.hidden=false;playError.textContent='Playback needs another tap. Please try again.'}});if(sessionStorage.getItem(key))connect('');
</script></body></html>`;
}
